### ISSUE TITLE
Badges undefined

### ISSUE THREAD

**Issue by kalilistic** [karashiiro/dalamud-plugin-dl-count-gh-badge#2]
Looks like the badges show up as undefined now. Not sure if your endpoint api expired or the recent download changes broke something.

**Comment by karashiiro** [comment]
Been meaning to fix it, I just need to switch the branch to `api5` and redeploy the function.

**Comment by karashiiro** [comment]
Updated, new Lambda URL is `https://vz32sgcoal.execute-api.us-east-1.amazonaws.com/`
